### ISSUE TITLE
Word speed not letting me set it above 400

### ISSUE THREAD

**Issue by zaidmohammed** [jsmnbom/ao3-enhancements#28] opened 2021-12-02 04:54 UTC
As I said in the title, the word speed option in the settings menu doesn't let me set the word speed above 400, which is making it hard for me to calculate how long it will take for me to finish a fanfiction.

**Comment by jsmnbom** [comment] 2022-01-02 22:11
Duplicate of https://github.com/jsmnbom/ao3-enhancements/issues/17 and fixed in future unreleased version. Sorry it's taking so long.

**Closed by jsmnbom** 2022-01-02 22:11 UTC
